// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD69OBzVRSybWElsSJsvexz2HUW051e9xI',
    appId: '1:1054247990610:web:c4afc7c73f24b67c77f68b',
    messagingSenderId: '1054247990610',
    projectId: 'swift-cart-aaece',
    authDomain: 'swift-cart-aaece.firebaseapp.com',
    storageBucket: 'swift-cart-aaece.firebasestorage.app',
    measurementId: 'G-JFQ41D59WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BiJAafQHydeF4xyfpw8M5rucieI8sLE',
    appId: '1:1054247990610:android:e703290a940f02ac77f68b',
    messagingSenderId: '1054247990610',
    projectId: 'swift-cart-aaece',
    storageBucket: 'swift-cart-aaece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8NwCrkJ0virF3Ab7bUgOPMhqmQpesOM',
    appId: '1:1054247990610:ios:eedd3596e3875c4777f68b',
    messagingSenderId: '1054247990610',
    projectId: 'swift-cart-aaece',
    storageBucket: 'swift-cart-aaece.firebasestorage.app',
    iosBundleId: 'com.example.swiftcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8NwCrkJ0virF3Ab7bUgOPMhqmQpesOM',
    appId: '1:1054247990610:ios:eedd3596e3875c4777f68b',
    messagingSenderId: '1054247990610',
    projectId: 'swift-cart-aaece',
    storageBucket: 'swift-cart-aaece.firebasestorage.app',
    iosBundleId: 'com.example.swiftcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD69OBzVRSybWElsSJsvexz2HUW051e9xI',
    appId: '1:1054247990610:web:b3dfa4dd9113d37677f68b',
    messagingSenderId: '1054247990610',
    projectId: 'swift-cart-aaece',
    authDomain: 'swift-cart-aaece.firebaseapp.com',
    storageBucket: 'swift-cart-aaece.firebasestorage.app',
    measurementId: 'G-GLWTMX68KR',
  );

}